### ISSUE TITLE
[PE-D][Tester E] Example in User Guide for 'Add' Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-4/tp#120]
![SCR-20240405-nhhn.png](https://raw.githubusercontent.com/raysonchia/ped/main/files/8e0001db-4270-459e-8b9d-4f83513296e0.png)
## Description
The example provided for adding a contact includes a placeholder for a phone number ("1234567") which does not conform to the valid format for Singapore. Since users in Singapore are accustomed to an 8-digit phone number format, this may lead to confusion and incorrect phone number entries.

## Steps to Reproduce
1. Navigate to the section of the user guide for adding a contact.
2. Observe the example provided for entering a phone number.

## Expected Behaviour
The example phone number should be in an 8-digit format consistent with Singapore's phone number standards to prevent any confusion for the users.

## Suggested Changes
- Update the placeholder phone number in the documentation and example to reflect the standard 8-digit format.
- Ensure that all example phone numbers in the documentation and application adhere to the local standards for the Singapore region.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: raysonchia/ped#1

**Comment by SamuelZero1** [comment]
Cannot change since this is a change in feature
