### ISSUE TITLE
[PE-D][Tester C] Doesn't account for invalid time period

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F14-4/tp#135]
Does not throw an error when given a time period that is invalid (backwards time where end time is before start time) or does not account for time periods that overflow past to the next day as there is only one date associated.
`mtg alex yeoh m/desc time/23-03-2024 1200-1157` gives

![image.png](https://raw.githubusercontent.com/ashleyclx/ped/main/files/d6ffaa3b-b41e-4a7b-bf33-888e98097968.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ashleyclx/ped#5

**Comment by yapxuanxuan** [comment]
Will include this in Planned Enhancements section in the DG as not allowed to fix. 
Not allowed to fix according to prof because it is not technically registering 'incorrect' or 'inconsistent' values.
