### ISSUE TITLE
[PE-D][Tester A] When assign 31 of Feb, instead of poping error, add the 28 Feb to current meeting

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F14-4/tp#138]
![image.png](https://raw.githubusercontent.com/LifHoshi/ped/main/files/d28f697b-b076-4b98-8ac1-6345d5c7d695.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: LifHoshi/ped#4

**Comment by yapxuanxuan** [comment]
Fixed this bug in PR #179 where 31st feb will raise an error instead of being rounded down to 28 feb. 
Unable to change the error message to be more specific as it is not allowed in v1.4
