### ISSUE TITLE
[PE-D][Tester A] Couldn't allow duplicate name exist

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F14-4/tp#141]
![image.png](https://raw.githubusercontent.com/LifHoshi/ped/main/files/9f1ce418-bee1-456d-8f83-870774ef8a68.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: LifHoshi/ped#5

**Comment by tahnya** [comment]
This is a feature of the app to ensure that the user does not add duplicate contacts.
