### ISSUE TITLE
[PE-D][Tester A] Cannot remove a single tag from person

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F14-4/tp#165]
Only can remove all tags at once

![image.png](https://raw.githubusercontent.com/LifHoshi/ped/main/files/3f455000-55e4-4abf-aa07-970f5b59d5f0.png)

![image.png](https://raw.githubusercontent.com/LifHoshi/ped/main/files/b335f2a7-7648-4e54-99f9-7b05c2d37edf.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: LifHoshi/ped#8

**Comment by yapxuanxuan** [comment]
This is not a feature that we claim to have in our UG. In addition, we clearly explained in our UG that if users wish to edit tags (remove or add), they would need to specify all the tags again. Though this could be a possible area for improvement.
