### ISSUE TITLE
[PE-D][Tester A] Invalid time format

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F14-4/tp#166]
Can assign backward step in time

![image.png](https://raw.githubusercontent.com/LifHoshi/ped/main/files/3ea527c6-442c-4c0f-bfd2-b047506aa10f.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LifHoshi/ped#9

**Comment by yapxuanxuan** [comment]
Will include this in Planned Enhancements section in the DG as not allowed to fix. 
Not allowed to fix according to prof because it is not technically registering 'incorrect' or 'inconsistent' values.
